# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  
  security:

      runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:     
      - uses: actions/checkout@v2
      - name: Dependency Check
        # You may pin to the exact commit or the version.
        # uses: dependency-check/Dependency-Check_Action@6451ab879ac4930a218fa5bd7393a04a3836b4a7
        uses: dependency-check/Dependency-Check_Action@1.0.0
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck  
           path: ${{github.workspace}}/reports 
           
      - name: Set up projects
        uses: security-code-scan/security-code-scan-add-action@v1.1

      - name: Build
        run: |
          dotnet restore
          dotnet build
        
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1.3
        
      - name: Upload sarif	
        uses: github/codeql-action/upload-sarif@v1
           

 

  
        
